'use client'

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { BellRing, CircleCheck, Clipboard, HandCoins, MapPin, RefreshCw, Settings, UsersRound, WalletCards } from 'lucide-react'
import type { EventWorkspace, UpdateEventRequest } from '@shared/contracts'
import { StatusPill } from '@/components/status-pill'
import { createApiClient } from '@/lib/api-client'
import { apiErrorMessage, runApiRead } from '@/lib/api-ui'
import { formatDate, formatMoney, titleCase } from '@/lib/format'

function Summary({ workspace }: { workspace: EventWorkspace }) {
  const event = workspace.event
  const confirmed = workspace.guests.filter(guest => guest.rsvp_status === 'yes').reduce((sum, guest) => sum + 1 + guest.plus_ones, 0)
  const pending = workspace.guests.filter(guest => guest.rsvp_status === 'pending' || guest.rsvp_status === 'maybe').length
  return <section className="member-card"><div className="member-workspace-summary"><div className="member-workspace-emoji">{event.event_emoji ?? '🎉'}</div><div className="member-workspace-copy"><span>{titleCase(event.event_type)} · {event.event_code}</span><h2>{event.name}</h2><p>{event.description || 'No description has been added yet.'}</p></div><StatusPill value={event.status} /></div><div className="member-workspace-stats"><div><span>Date</span><strong>{formatDate(event.event_date)}</strong></div><div><span>Confirmed</span><strong>{confirmed}</strong></div><div><span>Awaiting RSVP</span><strong>{pending}</strong></div><div><span>Budget</span><strong>{workspace.budget ? formatMoney(workspace.budget.total_budget, workspace.budget.currency_code) : '—'}</strong></div></div><div className="member-event-location"><MapPin size={16} /><div><strong>{event.venue_name || 'Venue to be confirmed'}</strong><span>{event.venue_address || [event.event_time, event.event_end_time].filter(Boolean).join(' – ') || 'Time to be confirmed'}</span></div></div></section>
}

function GuestDirectory({ workspace }: { workspace: EventWorkspace }) {
  return <section className="member-card" id="guests"><header><div className="member-section-title"><span><UsersRound size={18} /></span><h2>Guest list</h2></div><small>{workspace.guests.reduce((sum, guest) => sum + 1 + guest.plus_ones, 0)} people invited</small></header><div className="member-card-body member-directory">{workspace.guests.map(guest => { const name = guest.guest_name || guest.guest_phone || 'Guest'; return <article key={guest.id}><div className="member-directory-avatar">{name.slice(0, 2).toUpperCase()}</div><div><strong>{name}</strong><p>{guest.guest_phone || guest.guest_email || (guest.plus_ones ? `+${guest.plus_ones}` : 'Invited guest')}</p></div><StatusPill value={guest.rsvp_status} /></article> })}{!workspace.guests.length && <div className="member-empty">No guests have joined this event yet.</div>}</div></section>
}

function Announcements({ workspace, reload }: { workspace: EventWorkspace; reload: () => void }) {
  const canPost = workspace.event.status === 'active' && (workspace.capabilities.is_creator || workspace.capabilities.is_organiser || workspace.capabilities.linked_fund_permissions.includes('post_event_announcements'))
  const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function post(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setError('')
    try { await createApiClient().events.createAnnouncement(workspace.event.id, { title: String(form.get('title') ?? '').trim(), body: String(form.get('body') ?? '').trim() }); formElement.reset(); setBusy(false); reload() }
    catch (cause) { setError(apiErrorMessage(cause)); setBusy(false) }
  }
  return <section className="member-card" id="announcements"><header><div className="member-section-title"><span><BellRing size={18} /></span><h2>Announcements</h2></div></header><div className="member-card-body">{canPost && <form className="member-announcement-form" onSubmit={post}><input name="title" required minLength={3} maxLength={120} placeholder="Announcement title" /><textarea name="body" required minLength={3} maxLength={4000} rows={3} placeholder="Write an update for everyone attending…" /><button type="submit" disabled={busy}>{busy ? 'Posting…' : 'Post announcement'}</button></form>}<div className="member-announcements">{workspace.announcements.map(item => <article key={item.id}><div><strong>{item.title}</strong><span>{item.author_name} · {formatDate(item.created_at)}</span></div><p>{item.body}</p></article>)}{!workspace.announcements.length && <div className="member-empty">No announcements have been posted.</div>}</div>{error && <p className="member-form-error" role="alert">{error}</p>}</div></section>
}

function EventBudgetPanel({ workspace, reload }: { workspace: EventWorkspace; reload: () => void }) {
  const linkedFund = workspace.linked_fund
  const canManage = workspace.event.status === 'active' && Boolean(workspace.event.linked_fund_id) && (workspace.capabilities.is_creator || workspace.capabilities.is_organiser || workspace.capabilities.linked_fund_permissions.includes('manage_event_budget')) && (!linkedFund || linkedFund.fund.status === 'active')
  const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError('')
    try { await createApiClient().events.updateBudget(workspace.event.id, { total_budget: String(form.get('total_budget') ?? '').trim(), currency_code: String(form.get('currency_code') ?? workspace.event.currency_code) }); setBusy(false); reload() }
    catch (cause) { setError(apiErrorMessage(cause)); setBusy(false) }
  }
  return <section className="member-card" id="budget"><header><div className="member-section-title"><span><WalletCards size={18} /></span><h2>Event budget</h2></div>{workspace.event.linked_fund_id && <Link href={`/account/funds/${workspace.event.linked_fund_id}` as never}>Open linked fund</Link>}</header><div className="member-card-body">{workspace.event.linked_fund_id ? <><form className="member-budget-form" onSubmit={save}><label><span>Total budget</span><input name="total_budget" type="number" min="0" step="0.01" required defaultValue={workspace.budget?.total_budget ?? ''} disabled={!canManage} /></label><label><span>Currency</span><select name="currency_code" defaultValue={workspace.budget?.currency_code ?? workspace.event.currency_code} disabled={!canManage}><option value="BWP">BWP</option><option value="ZAR">ZAR</option><option value="USD">USD</option></select></label>{canManage && <button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save budget'}</button>}</form>{linkedFund && <div className="member-event-fund-summary"><div><span>Contribution goal</span><strong>{formatMoney(linkedFund.fund.goal_amount, linkedFund.fund.currency_code)}</strong></div><div><span>Raised</span><strong>{formatMoney(linkedFund.fund.totals.raised, linkedFund.fund.currency_code)}</strong></div><div><span>Available</span><strong>{formatMoney(linkedFund.fund.totals.balance, linkedFund.fund.currency_code)}</strong></div></div>}</> : <div className="member-empty">This event does not have a linked contribution fund, so it does not use a shared event budget.</div>}{error && <p className="member-form-error" role="alert">{error}</p>}</div></section>
}

function EventSettings({ workspace, reload }: { workspace: EventWorkspace; reload: () => void }) {
  const router = useRouter(); const event = workspace.event
  const canManage = event.status === 'active' && (workspace.capabilities.is_creator || workspace.capabilities.is_organiser)
  const canInvite = event.status === 'active' && canManage
  const code = event.share_code || event.event_code
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [copied, setCopied] = useState(false)
  async function save(formEvent: FormEvent<HTMLFormElement>) {
    formEvent.preventDefault(); const form = new FormData(formEvent.currentTarget)
    const request: UpdateEventRequest = { name: String(form.get('name') ?? '').trim(), description: String(form.get('description') ?? '').trim() || null, event_date: String(form.get('event_date') ?? ''), event_time: String(form.get('event_time') ?? '') || null, event_end_date: String(form.get('event_end_date') ?? '') || null, event_end_time: String(form.get('event_end_time') ?? '') || null, venue_name: String(form.get('venue_name') ?? '').trim() || null, venue_address: String(form.get('venue_address') ?? '').trim() || null }
    setBusy('save'); setError(''); try { await createApiClient().events.update(event.id, request); setBusy(''); reload() } catch (cause) { setError(apiErrorMessage(cause)); setBusy('') }
  }
  async function invite(formEvent: FormEvent<HTMLFormElement>) {
    formEvent.preventDefault(); const formElement = formEvent.currentTarget; const form = new FormData(formElement); const raw = String(form.get('phone') ?? '').trim(); const digits = raw.replace(/\D/g, ''); const phone = raw.startsWith('+') ? `+${digits}` : digits.length === 8 ? `+267${digits}` : `+${digits}`
    setBusy('invite'); setError(''); try { await createApiClient().events.inviteOrganiser(event.id, { name: String(form.get('name') ?? '').trim(), phone }); formElement.reset(); setBusy('') } catch (cause) { setError(apiErrorMessage(cause)); setBusy('') }
  }
  async function complete() {
    const amount = window.prompt('Estimated final spend (optional)', event.estimated_spend_amount ?? '')
    if (amount === null || !window.confirm('Mark this event as completed?')) return
    setBusy('complete'); setError(''); try { await createApiClient().events.complete(event.id, { estimated_spend_amount: amount.trim() || null }); setBusy(''); reload() } catch (cause) { setError(apiErrorMessage(cause)); setBusy('') }
  }
  async function leave() { if (!window.confirm('Leave this event? You will need the invitation code to rejoin.')) return; setBusy('leave'); setError(''); try { await createApiClient().events.leave(event.id); router.replace('/account/events') } catch (cause) { setError(apiErrorMessage(cause)); setBusy('') } }
  async function remove() { if (!window.confirm('Delete this event? It will disappear for everyone and cannot be restored from the website.')) return; setBusy('delete'); setError(''); try { await createApiClient().events.remove(event.id); router.replace('/account/events') } catch (cause) { setError(apiErrorMessage(cause)); setBusy('') } }
  async function copy() { try { await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setError('The invitation code could not be copied. Select and copy it manually.') } }
  return <section className="member-card" id="settings"><header><div className="member-section-title"><span><Settings size={18} /></span><h2>{canManage ? 'Event settings' : 'Attendance'}</h2></div></header><div className="member-card-body">{canInvite && <div className="member-invite-code"><div><span>Invitation code</span><strong>{code}</strong><small>Anyone with this code can join the event guest list.</small></div><button type="button" onClick={copy}><Clipboard size={14} /> {copied ? 'Copied' : 'Copy code'}</button></div>}{canInvite && <form className="member-organiser-form" onSubmit={invite}><label><span>Co-organiser name</span><input name="name" required maxLength={100} /></label><label><span>Phone</span><input name="phone" type="tel" required placeholder="+267 71 234 567" /></label><button type="submit" disabled={Boolean(busy)}>{busy === 'invite' ? 'Sending…' : 'Invite organiser'}</button></form>}{canManage ? <form className="member-form member-settings-form" onSubmit={save}><div className="member-form-grid"><label className="wide"><span>Event name</span><input name="name" required minLength={3} maxLength={200} defaultValue={event.name} /></label><label><span>Date</span><input name="event_date" type="date" required defaultValue={event.event_date} /></label><label><span>Start time</span><input name="event_time" type="time" defaultValue={event.event_time ?? ''} /></label><label><span>End date</span><input name="event_end_date" type="date" defaultValue={event.event_end_date ?? ''} /></label><label><span>End time</span><input name="event_end_time" type="time" defaultValue={event.event_end_time ?? ''} /></label><label><span>Venue</span><input name="venue_name" maxLength={200} defaultValue={event.venue_name ?? ''} /></label><label><span>Address or Maps link</span><input name="venue_address" maxLength={2000} defaultValue={event.venue_address ?? ''} /></label><label className="wide"><span>Description</span><textarea name="description" rows={4} maxLength={4000} defaultValue={event.description ?? ''} /></label></div><div className="member-form-actions">{workspace.capabilities.is_creator && !event.linked_fund_id && <button type="button" className="danger" onClick={remove} disabled={Boolean(busy)}>{busy === 'delete' ? 'Deleting…' : 'Delete event'}</button>}{event.status === 'active' && !event.linked_fund_id && <button type="button" onClick={complete} disabled={Boolean(busy)}>{busy === 'complete' ? 'Completing…' : 'Complete event'}</button>}<button className="primary" type="submit" disabled={Boolean(busy)}>{busy === 'save' ? 'Saving…' : 'Save changes'}</button></div></form> : workspace.capabilities.can_leave_event ? <div className="member-form-actions"><button className="danger" type="button" onClick={leave} disabled={Boolean(busy)}>{busy === 'leave' ? 'Leaving…' : 'Leave event'}</button></div> : null}{error && <p className="member-form-error" role="alert">{error}</p>}</div></section>
}

export function EventWorkspaceView({ eventId }: { eventId: string }) {
  const searchParams = useSearchParams(); const [workspace, setWorkspace] = useState<EventWorkspace | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [version, setVersion] = useState(0)
  const reload = useCallback(() => { setError(''); setVersion(value => value + 1) }, [])
  useEffect(() => { const controller = new AbortController(); runApiRead(call => createApiClient().events.workspace(eventId, call), controller.signal).then(setWorkspace).catch(cause => { const message = apiErrorMessage(cause); if (message) setError(message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [eventId, version])
  const notice = useMemo(() => searchParams.get('created') === '1' ? 'Event created. Share its invitation code when you are ready.' : searchParams.get('joined') === '1' ? 'You joined this event successfully.' : '', [searchParams])
  if (loading) return <section className="member-card"><div className="member-empty">Loading event workspace…</div></section>
  if (!workspace) return <section className="member-card"><div className="member-api-state error"><p>{error || 'This event could not be loaded.'}</p><div><button type="button" onClick={reload}><RefreshCw size={14} /> Try again</button><Link href="/account/events">Back to events</Link></div></div></section>
  return <><section className="member-pagehead"><div><Link className="member-back-link" href="/account/events">← My events</Link><h1>Event <em>workspace</em></h1><p>Keep organisers, guests, announcements, the venue, and event finances aligned.</p></div><nav className="member-page-actions" aria-label="Event workspace sections"><a href="#guests">Guests</a><a href="#announcements">Updates</a><a href="#budget">Budget</a><a href="#settings">Settings</a></nav></section>{notice && <p className="member-success-note"><CircleCheck size={16} /> {notice}</p>}{error && <p className="member-form-error" role="alert">{error}</p>}<Summary workspace={workspace} />{workspace.event.linked_fund_id && <section className="member-event-linked"><HandCoins size={18} /><div><strong>Event + Fund workspace</strong><span>Contributions, expenses, members and sponsorships live in the linked fund.</span></div><Link href={`/account/funds/${workspace.event.linked_fund_id}` as never}>Manage fund</Link></section>}<GuestDirectory workspace={workspace} /><Announcements workspace={workspace} reload={reload} /><EventBudgetPanel workspace={workspace} reload={reload} /><EventSettings workspace={workspace} reload={reload} /></>
}
